- README.md
The `dist/index.js` bit is confusing. Running without that gives you a working web UI.
Adding a screenshot to the README would help too.
> Skip the dist/index.js bit

- bin/cli.js
- client/package.json
- client/tailwind.config.js
- package-lock.json
- package.json
- server/package.json
- server/src/index.ts
This PR fixes some issues that are happening on Windows:
> Fix launch issues on Windows

- client/src/components/ToolsTab.tsx
Fixes #80
The inspector crashes when tool handlers return malformed responses. Specifically, when following the weather example from the docs, the inspector throws `TypeError: f.content.map is not a function` because the response structure doesn't match expectations.
- Replace type assertions with Zod schema validation to catch malformed responses
- Add error UI to display validation failures and help debug incorrect tool responses
- Update imports to use CallToolResultSchema for runtime type checking
- Uses `safeParse()` to validate without throwing
- Shows both invalid data and validation errors in the UI
- Maintains dark mode compatibility
> Add Runtime Type Validation for Tool Results

- bin/cli.js
- client/src/App.tsx
- client/src/components/Sidebar.tsx
We were hardcoded to port 3000 for the proxy server. This adjusts it via a query param (no other way to pass in env vars to the client)
> Respect custom server port

- client/src/components/ToolsTab.tsx
Dark Mode styling added for the Resource Viewer
Tested Image, Text and Resource Flows.
No
> Dark Mode and Word Wrap for Resource Viewer

- client/src/components/Sidebar.tsx
- client/tsconfig.app.json
> display inspector version in UI

- client/src/App.tsx
- client/src/components/ListPane.tsx
- client/src/components/PromptsTab.tsx
- client/src/components/ResourcesTab.tsx
- client/src/components/ToolsTab.tsx
Fixes #77
Add a button to the ListPane component that clears loaded items. This will allow the user to clear and reload resources, resource templates, prompts or tools when they expect the available items to have changed.
As noted in #77, once items (Resources, Resource Templates, Tools or Prompts) have been loaded they can't be loaded again. When adding resources or making changes to the other functionalities of the server while using the inspector, the available items might change. To load the fresh data currently requires reloading the inspector and setting up the connection again. By adding a button to clear items and any cursor that was set we can reload items without having to reconnect.
Tested manually by connecting to some of the example servers with the inspector.
No breaking …
> Add button to clear loaded items

- README.md
Linking to the docs site for easier discoverability.
> link to MCP docs site in readme

- client/src/App.tsx
Allows setting the Request Timeout in milliseconds with a "timeout" URL parameter
Enables testing of tools which take > 10s to respond.
This has been tested using the mcp-everything server 
No breaking changes.
@ashwin-ant this is intended to cover simple cases - I considered matching progress updates to requestids to reset the timer - but that seems over-engineered for the need.
> Allow setting the timeout with the "timeout" URL parameter

- client/src/components/ToolsTab.tsx
1) Tool Parameters were stale when switching between Tools causing incorrect messages to be sent. 
2) Tool List is emptied when "Clear" is selected, so invalid messages can't be sent.
Tool Tab was able to send invalid messages to Servers.
Tested against a Server under development.
No.
- [ X] I have added or updated documentation as needed
> Tool Tab - Parameter Handling Fixes.

- client/src/components/ToolsTab.tsx
Small fix for the legacy Tool Result result view. It does not have tailwind classes for dark mode, makes the result look like it's empty, since you get white text on a white background. Was walking through some examples from the documentation that still uses toolResult - initially tripped me up into thinking that there was a problem with my mcp server.
The legacy tool result does not have tailwind classes for dark mode.
Verified visually that the changes look the way they are supposed to visually.
Without fix:
With fix applied:
(none)
> Add dark mode support for the legacy Tool Result display

- client/src/App.tsx
- client/src/lib/hooks/useConnection.ts
- client/src/lib/hooks/useDraggablePane.ts
Refactors App.tsx to extract reusable logic into hooks, making the code more maintainable. The draggable pane logic and connection logic were mixed into the component, making it hard to understand and modify.
Tested locally by:
- Dragging the history pane up/down
- Connecting to MCP server
- Making requests and handling errors
- Verifying all existing functionality works as before
None. This is an internal refactor that doesn't affect the public API.
The refactor splits the code into:
1. useDraggablePane - handles drag behavior for resizable panes
2. useConnection - handles MCP client connection and request logic
> refactor: extract draggable pane and connection logic into hooks

- README.md
- bin/cli.js
- client/src/components/Sidebar.tsx
- server/src/index.ts
- Makes it so we can run `./bin/cli.js -e FOO=BAR /path/to/server` and have it pass the env var to the MCP server.
- Hides env vars by default in the UI to prevent accidental secret leakage
Addresses https://github.com/modelcontextprotocol/inspector/issues/94. 
Verified with command above.
No
> allow passing env vars to server from command line

- client/src/components/OAuthCallback.tsx
- client/src/lib/auth.ts
- client/src/lib/constants.ts
- client/src/lib/hooks/useConnection.ts
This PR adds refresh token support to the MCP Inspector's OAuth auth flow. When an access token expires, the inspector will now automatically attempt to refresh it using the stored refresh token before initiating a new OAuth flow. This improves the user experience by reducing unnecessary re-authentication prompts.
It also handles the case where:
1. An access token exists but is expired with no refresh token
2. The access token is invalid and refresh token is expired but exists
OAuth will start automatically upon clicking of "connect" in both cases. It already starts automatically if it receives a 401 and no access token exists.
The changes have been tested with an SSE server with OAuth implemented via Descope, specifically testing:
- Token expiration scenarios
- Missing refresh token …
> Add Refresh Token Support for OAuth

- server/package.json
- server/src/index.ts
While debugging an issue with starting the proxy server, its helpful to see a log when the app is listening successfully.
Tested on my Windows and Mac OS machines.
None
None
> Add server startup logging

- README.md
We were running into an error when using the inspector where we saw an error connecting.
After a couple minutes of testing and debugging, we realized our server worked when we added `node` before the command.
This is described here which is how we found it: https://modelcontextprotocol.io/docs/tools/inspector#inspecting-locally-developed-servers
> Update README to include node before the command

- package-lock.json
- package.json
- server/src/index.ts
`spawn-rx` follows symlinks when resolving executables, which breaks version manager shims on macOS. For example, when using Volta, `bun` incorrectly resolves to `volta-shim` instead of the `bun` executable. This PR works around the issue by bypassing `spawn-rx`'s path resolution on non-Windows platforms.
Closes #114
- Verified direct command execution works with Volta-managed `bun` on macOS
- Confirmed Windows path resolution remains untouched
None. This restores expected behavior on macOS while maintaining existing Windows functionality.
This could be a temporary fix while we investigate the underlying `spawn-rx` path resolution behavior. We may want to upstream a fix that handles Windows PATH resolution without affecting Unix shims.
Steps to reproduce the behavior:
1. On MacOS, use …
> fix(server) Avoid modifying path resolution for executables on MacOS

- client/src/components/ToolsTab.tsx
Fix an issue where string-values in the textarea did not change when using the Tools tab of the MCP Inspector (usually http://localhost:5173/#tools) and changing the selected tool.
The original problem triggered a tool manipulation error.
https://github.com/user-attachments/assets/1479965b-d045-477e-b3fa-f6d1bc3c0cc9
Attached is a recording that was tested operating in a browser.
https://github.com/user-attachments/assets/8d501e6d-947f-4ca7-9ed7-bd6cc5caefc5
No
> Fix ToolsTab Textarea value for clearing when switch tool

- client/bin/cli.js
- client/src/lib/auth.ts
- Fix OAuth callback routes in production builds by configuring serve-handler with proper SPA routing
- Adds a rewrite rule to serve index.html for all routes, allowing React Router to handle client-side routing
- Verify that OAuth callback works correctly in production builds
- Ensure that directly accessing /oauth/callback does not result in a 404 error
> Fix OAuth callback route in production builds

- client/src/components/PingTab.tsx
Removed color gradient flashing and focus effects from ping button and retitled it "Ping Server"
Not only was the the ping button style far out of step with the rest of the app's components, its bright color and rapid flashing draws the eye and can cause convulsions in individuals with photosensitive epilepsy.
Also the title "MEGA PING" with rockets and explosions seems incongruous with the actual function of the button, making me wonder the first time I used it if I was missing something, if it should be blasting pings at the server like a load test or something.  
A gif of the existing implementation can be found here:
https://github.com/orgs/modelcontextprotocol/discussions/186
Yes.
Nope.
- ~~I have added appropriate error handling~~
- ~~I have added or updated documentation as …
> Removing the all the hype from the ping button.

- client/src/App.tsx
- client/src/components/ResourcesTab.tsx
- client/src/lib/hooks/useConnection.ts
- client/src/lib/notificationTypes.ts
- package-lock.json
- package.json
**When the connected MCP server's capabilities include resource subscriptions:**
- Show a **Subscribe** or **Unsubscribe** button at the top of the selected resource panel of the Resources tab.
- Send subscribe/unsubscribe requests to the server according to the protocol spec.
- Track and manage subscribed resource URIs so that the UI knows which button to display for the selected resource.
- Allow `ServerNotificationSchema` messages to be handled.
**Incidental out-of band update:** Jetbrains IDE falls into a loop prompting for `npm install` to be run because these versions were not up to date.
- In package.json, package.lock.json, updated client and server versions to match inspector
- `"@modelcontextprotocol/inspector-client": "^0.5.1"`
- `"@modelcontextprotocol/inspector-server": …
> Add subscribe to resource functionality

- README.md
- client/src/App.tsx
- client/src/components/Sidebar.tsx
- client/src/lib/hooks/useConnection.ts
Add bearer token authentication support for SSE connections
This change enables testing of API key forwarding from remote MCP servers to underlying services. By supporting bearer token authentication in the Inspector UI, we can properly verify that authentication credentials are correctly propagated through the MCP server to our service endpoints. Depends on the usability, this can be replaced with a more general k-v "headers" section.
Tested with authenticated MCP servers requiring bearer tokens for connection. Verified that tokens are correctly sent in the Authorization header. The servers used SSE transport from the TypeScript SDK.
None. This is a backward-compatible feature addition that doesn't change existing behavior.
The bearer token is stored in localStorage for persistence …
> Add Bearer Token Support

- client/src/lib/hooks/useConnection.ts
I noticed that the version of the client was hardcoded to 0.0.1 while developing a sdk solution for ruby on rails.
after this modification , the client send the correct version 
```
"clientInfo" => {"name" => "mcp-inspector", "version" => "0.6.0"}
```
> feat: Fetch version from package.json in useConnection hook

- server/src/index.ts
> add sse accept header

- client/src/components/ToolsTab.tsx
- client/src/utils/__tests__/escapeUnicode.test.ts
- client/src/utils/escapeUnicode.ts
- package-lock.json
- package.json
> feat: Add utility function to escape Unicode characters in tool results

- client/src/components/ToolsTab.tsx
This fixes: https://github.com/modelcontextprotocol/inspector/issues/197
The other data types were reset, but an input was missed during implementation.
Created 2 tool
```ts
server.tool('add', { a: z.number(), b: z.number() }, async ({ a, b }) => ({
content: [{ type: 'text', text: String(a + b) }],
}))
server.tool('multiply', { a: z.number(), b: z.number() }, async ({ a, b }) => ({
content: [{ type: 'text', text: String(a * b) }],
}))
```
- Open the MCP Inspector app (version 0.6.0).
- Connect to the server via SSE (e.g., Transport Type: SSE, URL: http://localhost:3333/sse).
- In the "Tools" section, select the "add" tool (designed to add two numbers).
- Enter values in the input fields (e.g., a = 10, b = 5).
- Click "Run Tool" multiple times to confirm the "add" tool works consistently. …
> fix: set default value for input fields in ToolsTab component

- client/src/components/Sidebar.tsx
Resolves https://github.com/modelcontextprotocol/inspector/issues/205
Can reproduce and test in dev mode and prod build. Tested manually in latest Chrome, FF, Safari
issue seems to be with `newEnv[newKey] = value`. using `reduce` instead to explicitly maintain the order of entries seems to resolve the issue
> fix(sidebar): maintain order when changing values

- client/jest.config.cjs
- client/package.json
- client/src/__mocks__/styleMock.js
- client/src/components/__tests__/DynamicJsonForm.test.tsx
- client/src/components/__tests__/Sidebar.test.tsx
- client/src/components/__tests__/ToolsTab.test.tsx
- client/tsconfig.app.json
- package-lock.json
This PR adds configuration for adding UI tests as well as a few preliminary tests related to recent issues in this repo.
Manually testing UI inputs isn't really feasible for reproducing issues and avoiding new bugs, especially related to UI components that have many dynamic input fields.
Tests are run automatically in the GitHub actions.
None
> Add preliminary UI tests

- client/package.json
- package-lock.json
See: 
Dependabot PR: https://github.com/modelcontextprotocol/inspector/pull/176
Original alert: https://github.com/modelcontextprotocol/inspector/security/dependabot/15
For some reason Dependabot only updated the package-lock.json and not package.json, so I'm creating this to address the original issue.
Ran inspector locally and JSON code is still being highlighted as expected with no errors.
None
> Bump prismjs from 1.29.0 to 1.30.0

- client/src/App.tsx
This fixes https://github.com/modelcontextprotocol/inspector/issues/217 about the linter's warning that Hooks must be run in order each time.
* In App.tsx
- move the conditional that returns suspense if the path is oauth/callback to the end of the component after all hooks, rendering either suspense or the normal component.
- move `handleApproveSampling` and `handleRejectSampling` constants down below all the hooks for clarity. There are a lot of hooks so finding the end of them is a scroll, and these function constants aren't referenced until the rendering section below anyway.
- In the useEffect used to auto-connect if serverUrl is provided in URL params, add the `connectMcpServer` method as a dependency, quieting the ESLint complaint about it.
- Prettier fixed indenting at the end, so …
> Fix ESLint rules-of-hooks warnings

- client/src/components/ToolsTab.tsx
Refer to: https://github.com/modelcontextprotocol/rust-sdk/issues/73
JsonSchema has a integer type which not handle by inspector
via: https://github.com/modelcontextprotocol/rust-sdk/issues/73
No
> fix: prop.type not accept integer

- client/src/App.tsx
- client/src/components/Sidebar.tsx
- client/src/components/__tests__/Sidebar.test.tsx
- client/src/lib/hooks/useConnection.ts
Adds a Disconnect button in the style of the Reconnect button introduced in #216. I work on OAuth implementations (and Auth generally) so the creation of the connection is often the interesting part for me 😅 - this button will save me from needing to refresh the page whenever I need to restart the connection. 
Future improvements could include resetting the DCR client in local storage to make that process easier to test too, but figured I'd start small. 
Tested against a few MCP servers
> feat: Add lightweight Disconnect button

- client/src/App.tsx
Fixes a bug where the `useEffect` that wraps `connectMcpServer` runs repeatedly because `connectMcpServer` itself is not a stable callback reference. Every time the app re-renders, `connectMcpServer` is a different function, triggering the `useEffect` to run again.
I _think_ this fixes #250 - it certainly makes things much more stable for me though I have been getting a few scattered `ENOENT` errors as well.
Fixes a bug where the `useEffect` runs over and over and reconnects several times, which tends to overload the proxy and cause it to 500.
The old clicky clicky against my [existing](http://mcp-stytch-b2b-okr-manager.maxwell-gerber42.workers.dev/) MCP servers
> fix: Do not reconnect on rerender

- client/src/utils/configUtils.ts
Fixes #245 
Fixes a bug where the Client always assumes the Proxy server is running over `http`. Now the Client will use `https` when loaded over `https`.
Tested locally that `http://localhost:5173/` still connects to proxy server over `http`.
> fix: Use same protocol for proxy server URL

- client/src/components/PingTab.tsx
- client/src/components/PromptsTab.tsx
- client/src/components/ResourcesTab.tsx
- client/src/components/RootsTab.tsx
- client/src/components/SamplingTab.tsx
- client/src/components/ToolsTab.tsx
Fixed an issue where the gap between `TabsList` and `TabsContent` was inconsistent depending on the selected tab. This was caused by the `grid` class being applied directly to each `TabsContent`, which prevented the component from being hidden properly and caused the margin to be applied instead. To resolve this, I added a `div` directly under `TabsContent` and moved the classes that were applied to `TabsContent` to this inner div.
The following screenshot visualizes the unnecessary margin that was being applied to inactive `TabsContent`:
When reviewing the diff, it's helpful to [hide whitespace changes](https://github.com/modelcontextprotocol/inspector/pull/265/files?diff=unified&w=1) for better clarity.
Visually confirmed in the browser that the gap remains consistent across all tabs. …
> Fix inconsistent gap between TabsList and TabsContent

- README.md
- client/src/App.tsx
- client/src/components/Sidebar.tsx
- client/src/components/ToolsTab.tsx
- client/src/components/__tests__/Sidebar.test.tsx
- client/src/components/__tests__/ToolsTab.test.tsx
- client/src/lib/configurationTypes.ts
- client/src/lib/constants.ts
- client/src/lib/hooks/__tests__/useConnection.test.tsx
- client/src/lib/hooks/useConnection.ts
- client/src/utils/configUtils.ts
- package-lock.json
https://github.com/user-attachments/assets/504b33e3-8c24-4bb9-8bf5-b01fd4799980
The MCP Inspector now fully supports the [Model Context Protocol Progress Flow](https://spec.modelcontextprotocol.io/specification/2025-03-26/basic/utilities/progress/#progress-flow) specification, which enables:
- Optional progress tracking for long-running operations
- Added new configuration settings to the MCP Inspector for supporting this:
- `MCP_REQUEST_TIMEOUT_RESET_ON_PROGRESS`: Controls whether timeouts reset on progress notifications. Default: `true`
- `MCP_REQUEST_MAX_TOTAL_TIMEOUT`: Sets maximum total timeout for requests with progress notifications. Default: `60000` ms
1. `Run tool` button now shows as a spinner while the tool is running (and becomes disabled).
2. Improves error handling for …
> feat: Progress Support for Long Running Tool Calls ⏳

- client/src/components/Sidebar.tsx
This PR improves accessibility in the Sidebar component by adding
- proper `htmlFor` attributes to all form labels that reference the corresponding input/select elements
- matching `id` attributes to all form controls (inputs, selects) to associate them with their labels
- `aria-label` attributes to environment variable key and value inputs to provide proper labeling context
- `aria-expanded` attributes to all collapsible section toggle buttons (Environment Variables, Authentication, Configuration) to indicate their current state
I confirmed the label associations work in the browser and visually inspected the accessibility tree to verify proper values are set.
None.
> Enhance Sidebar component accessibility

- client/src/components/JsonView.tsx
- client/src/components/ToolsTab.tsx
This is the PR for the issue  #252  addressing the highlight tool errors.
##
This enhancement aims on highlighting the tool error. It was green text that has been displayed while tool error occurs. Now added a conditional check to highlight tool `error` in `red` and tool `success` in `green`.
Tested connecting with variety of servers -` server-everything` and `my-test-local-server`
No
The `isError` prop can utilized across various tabs to change the color of the string.
> feat: highlight tool errors in red text

- client/src/components/Sidebar.tsx
This fixes #273
* In Sidebar.tsx
- In Reconnect button handler, call onDisconnect before onConnect
The Reconnect button was creating a new connection, but subsequent messages sent to the server went with the previous sessionId, and were therefore rejected. See #273
* Connect to the `server-everything` server via SSE
* List Resources, List Tools
* Click Reconnect
* Repeat
* Connect to the `server-everything` server via STDIO
* List Resources, List Tools
* Click Reconnect
* Repeat
Nope.
The troubleshooting that led to this fix.
See: https://github.com/modelcontextprotocol/inspector/issues/273#issuecomment-2789895596
> Fix Reconnect handler

- client/src/App.tsx
- client/src/components/Sidebar.tsx
- client/src/components/__tests__/Sidebar.test.tsx
Add clear button for error notifications in MCP Inspector
Currently, there's no way to clear error notifications in the MCP Inspector UI, which can lead to a cluttered interface especially during long debugging sessions. This feature adds a clear button that allows users to remove all error notifications when they are no longer needed, improving the overall user experience.
- Tested in local development environment with MCP Inspector
- Verified clear functionality works with both single and multiple error notifications
- Tested button UI appearance in both light and dark themes
- Verified state management properly clears all notifications
No breaking changes. This is a purely additive UI feature that doesn't affect existing functionality.
- Implemented through prop drilling pattern from …
> feat: 🎸 Add clear button for error notifications

- client/src/components/JsonView.tsx
Tool error not highlighted for lengthy strings. This PR fixes #299 
When I was testing the sample LLM tool found that the tool error not being highlighted due to the missing condition in the lengthy strings.
- Tested the sample LLM tool call and made sure the error is highlighted 
- Tested the normal tool calls flow with server-everything
There are no breaking changes
This is bug is related to the enhancement #275
> fix: missing condition for lengthy strings

- README.md
- client/src/App.tsx
- client/src/components/Sidebar.tsx
- client/src/components/__tests__/Sidebar.test.tsx
- client/src/lib/hooks/useConnection.ts
This change adds a Header Name field to the sidebar. It overrides the "Authorization" default name.
Some servers use a custom header name (e.g., Vercel Preview). The current feature doesn't support these servers.
I've added unit tests and tested it manually
No breaking changes.
Please let me know if it requires any changes, and thanks for the great project!
> Enable Authentication header name configuration

- client/src/lib/hooks/__tests__/useConnection.test.tsx
- client/src/lib/hooks/useConnection.ts
This is a candidate PR for issue #269.
Fixes #269
This PR adds a representation of initialize request and response to the History panel.
The information in server's `initialize` response is very helpful - notably `instructions` and `serverCapabilities`. It would be great to see it in the inspector.
Tested connecting with variety of servers - `server-everything`, `linear-mcp-server`
No
I am using the existing `pushHistory` method to push the request / response for `initialize` RPC messages.
There's a rub: the actual RPC request is abstracted in `Client.connect` (including `notification/initialized`).
This means that the payload pushed to history can potentially diverge from the one in the API client. I took the conservative approach, by representing the request with `method` only - I think …
> feat: Show initialize request/response in History panel (#269)

- README.md
This PR fixes a missing `node` command in the README.md file. The current documentation omits this necessary command prefix in one of the instructions, which could cause confusion for users trying to follow the setup steps.
When following the instructions in the README.md, users would encounter an error because one command line is missing the `node` prefix. This small documentation fix ensures that users can successfully execute the commands as written without having to troubleshoot or infer the missing part.
I verified that the command works correctly with the `node` prefix added. The documentation now accurately reflects the correct command syntax needed to run the tool.
None. This is purely a documentation fix that doesn't affect any functionality.
This is a simple documentation fix to …
> fix:README.md missing character

- client/src/components/Sidebar.tsx
This PR fixes the **console warning** in sidebar in logging level select element. Added key attribute in the select element to fix this
This solves the console warning associated with the sidebar  logging level select element.
Tested in the browser console
There are no breaking changes.
> fix: console warning in sidebar

- client/src/components/PromptsTab.tsx
- client/src/components/ResourcesTab.tsx
This PR closes #301 
There is no way we can get the right sections cleared out once a selection has been made on the `Resources` and `Prompts` tabs. It takes a inspector restart to get them back to initial state.
This PR resets the display section on the right side when `Clear` button is hit.
Attaching the below video for reference of what was fixed in this PR.
https://github.com/user-attachments/assets/f1d4d50f-3468-436e-84ac-d70028e11e25
- Running test cases were successful. 
- Tested if the change has any negative impact on the respective `Resources` and `Prompts` tab and tested flows in other tabs as well. 
There are no breaking changes in this PR
> feat - Display section reset on clear button hit

- client/src/components/DynamicJsonForm.tsx
- client/src/components/ToolsTab.tsx
- client/src/components/__tests__/DynamicJsonForm.test.tsx
Fixes #281 
Currently, when the `ToolsTab` cannot determine the type of a property (for example... if it a union type or something similarly complex) it defaults to a String input. This is rarely the correct choice - leading to bugs like #281 and #234.
The `DynamicJsonForm` component is waaaay nicer - and lets the caller set the exact value of the property - whether it is an object, array, or some other primitive type. Falling back to the JsonForm when we don't know how to interpret the type is nice, and feels like a reasonable solution compared to supporting arbitrarily complex nested JSON schema attributes.
Tested against #281 by creating a MCP Tool that takes in a nullable array of strings:
```typescript
server.tool("arrayTest", {arr: z.nullable(z.array(z.string()))}, async ({arr}) => …
```
> fix: When tool type cannot be determined, use DynamicJsonForm

- client/src/App.tsx
This PR is to fix a `reset error` in `prompts tab` where prompt results weren't reset when switching between prompts. 
With this fix, the results will be reset and rightly populated every time on selecting a new prompt.
Prompt results were not reset when switching between prompts. 
This results in confusion since the previously selected prompt's result always stays and never gets reset unless user hits refresh.
The below is the reset error observed in the `Prompts` tab.
https://github.com/user-attachments/assets/e88387a5-3617-4553-82b6-b2fc1a92ee65
- Tested by switching between prompts, hitting clear button and observed the previous results to be reset and current results to be rightly populated. 
- Ran local test cases successfully
This PR doesn't include any breaking changes
> fix - Reset Prompt results

- client/jest.config.cjs
- client/src/lib/hooks/useConnection.ts
- package-lock.json
- package.json
- server/src/index.ts
* In server/index.js
- add get/post handlers for /mcp
- amend console log on SSE connect, with deprecation message
- add /stdio GET handler and refactored /sse GET handler to not also do stdio. Each transport has its own handler now
- add required headers to streamable-http request
- add `mcp-session-id` and `last-event-id` to `STREAMABLE_HTTP_HEADERS_PASSTHROUGH`
* In /client/src/lib/hooks/useConnection.ts
- in connect function
- create server url properly based on new transport type.
The [PR that added support for streamable-http servers](https://github.com/modelcontextprotocol/inspector/pull/294) was incomplete, but it actually seemed to work because the proxy server had `/sse` and `/message` endpoints. 
This adds `/mcp` GET/POST endpoint support to the MCP proxy server, and slightly …
> Fix support for streamable-http connections

- client/src/utils/__tests__/schemaUtils.test.ts
- client/src/utils/schemaUtils.ts
When argument to a tool is not specified it should not be default and send via MCP request as a NULL value.
The tool must be defined so that a parameter is `nullable` in its JSON Schema in order to send a `null` value. If it is not marked as nullable, then `null` should **not** be sent—omit the parameter instead. This avoids schema validation errors and ensures proper behavior with strict clients like TypeScript SDKs.
The [MCP-ODBC](https://github.com/OpenLinkSoftware/mcp-odbc-server) includes tools with optional parameters. These are not nullable by default, and the TypeScript SDK rejects inspector requests when `null` is incorrectly included. This change was tested against that server to confirm that unspecified parameters are properly omitted, and requests are accepted.
No breaking …
> When argument to a tool is not specified it should not be default and send via MCP request as a NULL value.

- .github/workflows/main.yml
- cli/package.json
- client/package.json
- package-lock.json
- package.json
- server/package.json
* In main.yml
- reversed a change from last release that did an explicit build during the publish step, because the prepare script was no longer in package.json
* In package.json
- replaced prepare script, which will cause automatic build after npm install
- set version to 0.11.0
- set versions of inspector-cli, inspector-client, and inspector-server to  0.11.0
* In package.lock.json
- updated versions of inspector, inspector-cli, inspector-client, and inspector-server to  0.11.0
* In cli/package.json
- set version to 0.11.0
- set versions of sdk to 1.10.2
* In client/package.json
- set version to 0.11.0
- set versions of sdk to 1.10.2
* In server/package.json
- set version to 0.11.0
- set versions of sdk to 1.10.2
StreamableHttp is available now and people need to test it. 
Build, test, …
> Bump version to 0.11.0

- client/bin/client.js
* In `client/bin/client.js` 
- in the request handler passed to `createServer`, expand the handler options to include "Cache-Control" header for
- index.html - "no-cache, no-store, max-age=0"
- assets/** - "public, max-age=31536000, immutable"
I've noticed that on a new version of the inspector, I have to go to the browser's devtools panel and clear site data then reload the page.
* The assets are hashed and immutable, so caching should always be allowed for them
* The index.html file is the problem, because if cached, it will point to old assets, and therefore needs to have caching turned off
* This PR adds appropriate headers to the index.html and assets that are served.
Ran server locally and observed headers sent to the client:
Nope.
> Fix the inspector caching problem

- cli/package.json
- client/package.json
- package-lock.json
- package.json
- server/package.json
This PR fixes #374 
upgraded the sdk version to 1.11.0
Yes, it is tested using everything server
No
> fix: sdk version upgrade

- README.md
- client/src/App.tsx
- client/src/utils/configUtils.ts
I plan to use this in my workshops about MCPs and in my workshop environment I want to have an iframe of the inspector. Each exercise has a different URL for the MCP server for that exercise so having the URL of the config coming from the URL can be quite helpful.
✅ Yes
https://github.com/user-attachments/assets/7e8acbf3-13e7-4934-900c-73665c17fd49
✅ No breaking changes
My current WIP workshop repo can be found here: https://github.com/epicweb-dev/mcp-fundamentals
> feat(client): add search param configuration

- server/src/index.ts
Reverts modelcontextprotocol/inspector#380
I realized the problem is already be fixed in the #428, and there's no need to have to refactor that one to remove most of this one's changes.
> Revert "fix: handle the client disconnect so that the server does not crash."

- README.md
This adds a quick start example to just run the inspector and serve the UI without any extra config. This seems to be missing from the `README.md`.
People probably want to just dive right in with it right away. There is no quick start example, all the other examples are detailed config options for more narrow use cases.
Locally
None
> Add quick start example

- client/src/lib/hooks/useConnection.ts
- server/src/index.ts
Added custom header support.
See #395 
The header parser implementation has been tested with a server driven by Spring-AI locally.
This change will impact services that rely on the "Bearer " prefix for authentication.
> feat: support custom authorization headers, fix #395

- client/src/lib/hooks/useConnection.ts
- server/src/index.ts
* In server/src/index.ts
- add delete handler for /mcp endpoint
- gets the server transport for the sessionId
- calls terminateSession on it
- removes the webapp and server transports for the sessionId from the maps
- returns status 200 to the client.
* In client/src/lib/hooks/useConnection.ts
- import Transport
- add useState for clientTransport, type Transport or null initialized to null
- in connect() function
- move creation of client transport down a ways, just before calling client.connect with it
- immendiately efter calling client.connect, call setClientTransport with the connected transport (has to happen after, so that what's saved has the abort controller, etc. otherwise it doesn't work to save it prior.
- in disconnect() function
- immediately call …
> Send HTTP DELETE on streamable transport disconnect

- README.md
- client/src/App.tsx
- client/src/components/Sidebar.tsx
- client/src/lib/hooks/useDraggablePane.ts
Fixes https://github.com/modelcontextprotocol/inspector/issues/457
Vibe-coded with Cursor
Make left sidebar resizable so long URLs can be viewed in their entirety.
Sidebar narrow so can't see full URL
Sidebar can be expanded to see full URL
```
npm run dev
```
and then resize in browser
No
> Resizable left sidebar

- .github/workflows/e2e_tests.yml
- client/package.json
- package-lock.json
Update the `radix-ui/react-*` components and the `lucide-react` icons.
Periodic package update reduce the future maintenance effort.
After each package update, I checked various UI elements using it against the MCP "everything" server.  I also ran the new `npm run test:e2e` tests.
No.
> chore: Update radix-ui components and icons

- CONTRIBUTING.md
- README.md
- client/bin/client.js
- client/bin/start.js
- server/src/index.ts
Bind client to localhost instead of all interfaces to match server
Complete the security hardening started in https://github.com/modelcontextprotocol/inspector/commit/e8e990987c544f9e9c2603acbf990866f9c91891 by also binding the client to localhost only.
Previously only the server was protected while the client remained exposed to the network,
allowing attackers to access the server through the client as a proxy.
Changes:
- Add HOST environment variable support to client (prod mode)
- Configure Vite dev server to bind to localhost by default
- Update browser auto-open URLs to use actual host instead of hardcoded 127.0.0.1
- Fix missing cancelled parameter in startProdClient function
|Before|After|
|--|--|
|![CleanShot 2025-06-18 at 17 56 …
> fix: bind client to localhost to match server

- client/src/components/ToolsTab.tsx
- client/src/components/__tests__/ToolsTab.test.tsx
There's a bug in the number inputs for tools where you can't enter negative numbers. (You can paste them or use the little browser UI down arrow, but that thing is a joke). I can create a minimum test MCP server if requested, but you should be able to see the issue using any number number. 
Number inputs were immediately converting values to Number() on every keystroke, which prevented users from typing negative numbers since the intermediate "-" character cannot be converted to a valid number.
Now the input stores the raw string value and only converts to Number when the value is non-empty, allowing proper negative number entry.
- Manually with an MCP server that exposes floats as params. 
- Added a unit test, but that might've been overkill 
**Real world use case:** A tool that exposes …
> fix: allow typing negative numbers in tool parameter inputs

- package-lock.json
Clone and run `npm install`; `package-lock.json` immediately has changes -- `engines` are added.
Running `npm install` after a fresh clone should not result in any changes to NPM files.
I suspect this was missed in PR #473 
`npm run test` and `npm run test:e2e` both pass all tests.
No
> chore: Add engines to `package-lock.json`

- cli/src/cli.ts
If started from cli.js, the token isn't being created/passed to the server
> fix startup of webclient through cli

- README.md
Attempts to execute this command will fail: npx @modelcontextprotocol/inspector --cli http://127.0.0.1:8000 --transport http. The error indicates that --method is a mandatory parameter: "Method is required. Use --method to specify the method to invoke. Failed with exit code: 1". That's why the right command may look like this: npx @modelcontextprotocol/inspector --cli http://127.0.0.1:8000 --transport http --method tools/list.
> Missing mandatory parameter in the Inspector's CLI command

- cli/scripts/cli-tests.js
- cli/src/transport.ts
At the moment, the CLI tool expects that remote MCP servers, either using SSE or streamable HTTP transport, have certain endpoints or fragments -- `/sse` and `/mcp`, respectively. These specific routes are not part of the MCP spec, nor should it be expected.
I also added a check to make sure a URL is provided if STDIO isn't picked, erroring out if not.
Fixes: #594
See: #578. Recreating it here with a pared-down version that addresses the review comments. I needed this locally now and am sharing it. Please merge whichever.
I have a local MCP server on a root endpoint (`/`) served by a little Express server (not `/mcp`). Currently, I can't use the inspector CLI as a little integration test in development. Only now can I do:
```console
$ ./build/cli.js --cli --transport http …
```
> [cli] Don't force specific endpoints for remote servers

- .github/workflows/cli_tests.yml
- cli/scripts/cli-tests.js
- cli/src/cli.ts
- cli/src/index.ts
Right now, the inspector has a CLI feature as well as a series of tests. However, they're not currently run in CI. For the moment, they are only triggered on file changes in the CLI folder, as AFAICT it is currently a separate code base.
I pushed up a PR that touches files in the CLI folder (#595) and had to manually show the test run results. 
The check itself within the GitHub UI should be sufficient. 
N/A
> Run the CLI tests in CI

- client/bin/start.js
Invoke the server with an argument notation that tolerates a dash-option.  Closes #649 
There is an argument handling regression, and it is helpful to be able to pass a dash-option to the MCP server command.
Running locally with both CLI and config file options.
No
This is not related to parsing of the initial command by `cli/build/cli.js` (package entry point)., i.e., no quoting or use of `--` separation will address this bug.  Arguments are parsed correctly, but the passing of the command and args during server invocation is the problem.
> fix: Argument notation to allow parseArgs to parse leading dash-options

- client/bin/start.js
This fixes the regression introduced in dc5fa6a where `npx .` (without any arguments) fails with:
```
TypeError [ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL]: Unexpected argument ''. This command does not take positional arguments
```
Commit dc5fa6a changed the argument passing from using spread syntax to directly including empty strings when no command/args are provided. The `parseArgs` function in the server interprets these empty strings as unexpected positional arguments.
Reverted to using the spread operator approach that was used before dc5fa6a. This is more idiomatic and avoids creating empty strings that would need to be filtered out.
|Before|After|
|--|-|
|<img width="1804" height="686" alt="CleanShot 2025-08-05 at 12 02 13@2x" …
> bugfix: fix `npx @modelcontextprotoco/inspector` failing on main

- .gitignore
- .prettierignore
- README.md
- cli/scripts/cli-tests.js
- cli/src/cli.ts
- client/bin/start.js
- client/e2e/cli-arguments.spec.ts
- client/src/App.tsx
- server/src/index.ts
When launching the inspector with `--config`, automatically set the transport
dropdown and server URL based on the config file contents. This eliminates
the need to manually switch between `stdio/sse/streamable-http` in the UI.
- Use discriminated union for ServerConfig to properly type different transports
- Detect transport type and URL from config, pass via query params
- Maintain backwards compatibility for configs without explicit `type` field
- Add comprehensive tests for the new functionality
Improves UX by making the config file the single source of truth for
server settings.
Tested manually with different configs:
E.g. with a `stdio` based config:
```
// mcp_dev_config.json
{
"mcpServers": {
"default-server": {
"command": "uv",
"args": [
"run",
"--with",
"mcp[cli]",
"mcp",
"run", …
```
> feat: Auto-detect transport type from config files

- client/src/components/__tests__/AuthDebugger.test.tsx
- client/src/lib/oauth-state-machine.ts
- package-lock.json
- package.json
Bump the MCP SDK pin from `^1.17.0` to `^1.17.2`, to update the debugger to the latest AS metadata endpoint discovery method (`discoverAuthorizationServerMetadata` introduced in https://github.com/modelcontextprotocol/typescript-sdk/pull/652) and include the CORS retry bug fix introduced in `1.17.2` (https://github.com/modelcontextprotocol/typescript-sdk/pull/827).
Needed to connect Inspector's auth debugger to MCP servers that use Azure for AS. Needed support for metadata at `/.well-known/openid-configuration`, and needed CORS fix so it didn't fail on earlier attempted incorrect endpoints.
Run all tests locally (and needed to update the mocks to the new method).
As tests were changed, also manually tested against an OOB MCP server (Neon's) and a custom one using Azure AD.
- It shouldn't, …
> Bump auth SDK to use Improved AS Discovery

- client/src/lib/hooks/useConnection.ts
* In useConnection.ts
- During initialization, if there is an error immediately following the client sending `logging/setLevel`, pop up a toast with the message `Server declares logging capability but doesn't implement method "logging/setLevel"`
* #699 reported an "unknown regression" when connecting to a server. The problem was diagnosed by @KKonstantinov as stemming from #611 which sends a `logging/setLevel` message during initialization if the server advertises support for the `logging` capability. 
* This issue was also reported in #696.
The [MCP spec for logging](https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging) states two relevant things:
> Servers that emit log message notifications MUST declare the logging capability:
>
> ```json
> {
> …
```
> Add toast for misconfigured logging

- client/src/components/__tests__/AuthDebugger.test.tsx
- client/src/lib/oauth-state-machine.ts
The guided auth flow did not support static client fallback after dynamic client registration (DCR) had failed. This doesn't meet the MCP spec.
The [MCP spec authorization](https://modelcontextprotocol.io/specification/2025-06-18/basic/authorization) states:
> "Authorization servers and MCP clients **SHOULD** support the OAuth 2.0 Dynamic Client Registration Protocol ([RFC7591](https://datatracker.ietf.org/doc/html/rfc7591)).". The lack of fallback here means the auth debug flow doesn't meet MCP spec as it mandates that resource servers **MUST** support DCR.
This PR adds a static client credentials attempt as a fallback for failed DCR. If DCR is supported and successful, the static client will not be used. 
Addresses #683.
Tested locally with MCP servers with both DCR and static fallback. …
> Fix: Pre-registered Client ID as fallback to DCR

- client/src/components/__tests__/AuthDebugger.test.tsx
- client/src/lib/__tests__/auth.test.ts
- client/src/lib/auth.ts
- client/src/lib/hooks/__tests__/useConnection.test.tsx
- client/src/lib/hooks/useConnection.ts
- client/src/lib/oauth-state-machine.ts
Fixes: https://github.com/modelcontextprotocol/inspector/issues/580, https://github.com/modelcontextprotocol/inspector/issues/587
This PR introduces centralized scope discovery logic through a new `discoverScopes` function  and integrates it across both OAuth authentication flows to ensure consistent scope resolution behavior.
Also related: https://github.com/modelcontextprotocol/inspector/pull/705
**New `discoverScopes` Function**: 
- Discovers OAuth scopes from authorization server metadata
- Prioritizes Protected Resource Metadata scopes over Authorization Server metadata scopes 
- Returns space-separated scope string or `undefined` if no scopes available
- Handles discovery failures gracefully with debug logging
**Integration Points**:
- **Quick Flow (`useConnection`)**: Integrates …
> feat: unify OAuth scope discovery between automatic and manual flows

- client/src/App.tsx
- client/src/components/Sidebar.tsx
- client/src/lib/hooks/useConnection.ts
- client/src/lib/notificationTypes.ts
- server/src/index.ts
* Remove handling of out-of-spec `notification/stderr` messages. It's not a thing. See https://github.com/modelcontextprotocol/servers/pull/2469
* Inspect the `stderr` output of STDIO servers and attempt to assign an appropriate [RFC 5424 Syslog Protocol level](https://datatracker.ietf.org/doc/html/rfc5424#section-6.2.1) before sending as leveled logging message to the client, as per [MCP Logging Spec](https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging#log-levels).
A [recent change](https://github.com/modelcontextprotocol/servers/pull/2469) to the `server-everything` reference server raised the point that `notification/stderr` is not a valid MCP message type. It was only added to the server because handling for it existed in the Inspector, [added some time …
> Handling of stderr on STDIO servers

- Dockerfile
- README.md
* In README.md
- Add the command to start the Inspector UI in a Docker container
* In Dockerfile
- use `current-alpine3.22` as the base image 
Instruction on how to launch in container is currently missing from the README. I was holding off to see if the container base image would be fixed, as `24-slim` has a high vulnerability CVE which remains unfixed which allows running commands on the host as root. I chose the alpine image because all the slim variants have medium and low vulnerabilities. This image was the lowest vulnerability level running Node 24.
This is testing the command added to the README with the current version in ghcr.io. We'll have to test the build with alpine after merge.
Nope.
> Add Docker container startup command to README.md

- cli/src/index.ts
- cli/src/utils/awaitable-log.ts
This PR solves this issue:
https://github.com/modelcontextprotocol/inspector/issues/753
The `console.log` was not blocking until its completion so the process.exit(0) was being hit before it could finish. This change uses the callback function of process.stdout.write to make an awaitable log command.
Tested with the [GitKraken MCP](https://github.com/gitkraken/gk-cli) to reproduce the issue, and then tested again with the fix.
```
node build/cli.js --cli gk mcp --method tools/list
```
None
I created a utils directory and single file for the utility method, `awaitableLog`. I would be happy to change where that function lives, or even inline its logic into the place it is used.
Fixes #753
> Make cli output awaitable to prevent truncating the result

- .gitignore
- cli/package.json
- cli/scripts/cli-header-tests.js
- cli/src/index.ts
- Introduced integration tests for recently added header functionality in a new script `cli-header-tests.js`.
- Updated the `package.json` to include the new test script and modified the existing test command to run all tests.
- Adjusted the main CLI exit behavior to ensure proper termination in CI environments, after it was removed here: https://github.com/modelcontextprotocol/inspector/pull/716
- A separate PR added an awaitable log function instead to resolve the truncation in a different way: https://github.com/modelcontextprotocol/inspector/pull/754
(Also added `.claude/settings.local.json` to `.gitignore` to prevent local Claude Code settings from being tracked.)
Ran tests locally and in CI
No
> Add CLI header integration tests and update test scripts

- cli/package.json
- client/package.json
- client/src/lib/hooks/useConnection.ts
- package-lock.json
- package.json
- server/package.json
* In useConnection.ts
- push the `logging/setLevel` message onto the message history stack so it is clear in the Inspector that it has been sent.
* In all package.json and package-lock.json,
- bump the TS SDK to the latest version 1.17.5
Previously, we were sending a `logging/setLevel` message to any server that advertises support for logging, [as per the spec](https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging#setting-log-level). However, we were not showing that message in the message history. This PR's only functional change is to show that message.
Also, the latest Typescript SDK has support for [automatic handling of logging level](https://github.com/modelcontextprotocol/typescript-sdk/pull/882). This PR bumps the TS SDK version to the latest version, …
> Auto log-level handling support

- client/src/App.tsx
- client/src/__tests__/App.config.test.tsx
- client/src/__tests__/App.routing.test.tsx
- client/src/components/HistoryAndNotifications.tsx
- client/src/components/__tests__/HistoryAndNotifications.test.tsx
- client/src/lib/hooks/useConnection.ts
This pull request adds two buttons that can be used to clear the history and server notification panels. Fixes #780.
When dealing with different MCP servers or doing many requests the history and notification panels can become quite cluttered so that it is hard to find which entries belong to which action I did.
Checked manually and added a test case for each button.
No
No
> feat: add clear buttons for request history and server notifications

- server/src/index.ts
Adds a mechanism to dynamically inject and update HTTP headers for ongoing proxy sessions, resolving an issue where headers introduced after the initial handshake (e.g, Mcp-Protocol-Version) were not being forwarded to the server on subsequent exchanges.
In `src/index.ts`:
- Added `sessionHeaderHolders`, a `Map` to store the most recent set of headers for each active session ID.
- Added `createCustomFetch`, a new helper function that creates a `fetch` wrapper. This wrapper merges the session headers from `sessionHeaderHolders` with the request-specific headers from the SDK (like `Content-Type`)
- In `createTransport`, use `createCustomFetch` for both the `StreamableHTTPClientTransport` and `SSEClientTransport`. This injects the dynamic header logic into the transport layer.
- In `/mcp`, …
> Implement dynamic header injection for proxy transports. 

- client/src/App.tsx
- client/src/components/Sidebar.tsx
- client/src/components/__tests__/Sidebar.test.tsx
- client/src/lib/hooks/__tests__/useConnection.test.tsx
- client/src/lib/hooks/useConnection.ts
* In App.tsx
- Add state for connectionType
- Fetch connectionType from localstorage if present
* In Sidebar.tsx
- Add dropdown for connectionType, only visible if transport type is not stdio
* In Sidebar.test.tsx
- set connectionType to "proxy"
* In useConnection.ts
- add connectionType param, defaulting to "proxy"
- add state for mcpSessionId
- Only check proxy health if the connection type is proxy
- create a serverUrl variable which will either be the proxy url OR the server url depending upon the connection type
- added captureResponseHeaders function to extract the protocol-related headers from a response.
- when creating transport options and connectionType is "direct" and transportType is not "stdio",
- add the appropriate `Accept` and `Content-Type` headers
- capture the protocol …
> Allow bypassing proxy with Connection Type dropdown 

- client/src/lib/auth.ts
This reverts commit 36b9acc97e0f142dab6430c91a71131790523cad which filtered out `client_secret` from being populated in local browser storage in response to a CodeQL advisory.
In OAuth there is a notion of a “client id” and a “client secret”, and also a “public” client and a “confidential” client:
* **Client id**: an identifier for a client that can be shared publicly, useful for scoping access tokens to a single client, and as a key to reference the rest of the registered client’s metadata (client name, redirect URI’s, logos etc.).  This ID is generally not treated as sensitive, and can be displayed in UI’s etc.   
* **Client secret**: an additional secret that is NOT public, and is expected to be kept private to a backend component. Leaking a client secret is problematic when an …
> Revert "fix: filter out client_secret when storing OAuth client information"

- client/src/App.tsx
- client/src/lib/hooks/__tests__/useConnection.test.tsx
- client/src/lib/hooks/useConnection.ts
Fix OAuth token injection when default `"Bearer "` header is present, preventing infinite auth loops
Closes #829
This change fixes a critical authentication bug that caused infinite OAuth loops in the inspector. The issue occurred when users had the default `customHeaders` configuration with an empty "Bearer " placeholder header. The authentication logic would send "Bearer " (without an actual token) to the server, which would return a 401 error, triggering OAuth flow, but the same empty header would be sent again, creating an infinite loop.
The root cause was that the OAuth token injection logic only triggered when `finalHeaders.length === 0`, but the default configuration always included a placeholder header `{ name: "Authorization", value: "Bearer ", enabled: true }`, so the condition …
> fix: enhance OAuth token handling in useConnection hook to prevent infinite auth loops

- cli/src/index.ts
* In `cli/src/index.ts`
- load `package.json` from `../` or `../../` depending on file existence in parent.
- move the load of `package.json` into `callMethod` function, which is the only place it is used, and is closer to where it is referenced.
In #544, a change to `cli/src/index.ts` was introduced that reads `package.json` from one level up (`../package.json`). As reported in #834, It fails when running `@modelcontextprotocol/inspector` from the command line.
* It works if the project is checked out locally, because the `package.json` of the workspace packages are present. 
* However, they are not included in the main `inspector` build, so it does not work in [`@modelcontextprotocol/inspector`](https://www.npmjs.com/package/@modelcontextprotocol/inspector?activeTab=code).
* We _can_ …
> Fix cli package.json import

- client/src/components/PromptsTab.tsx
- client/src/components/ui/combobox.tsx
Fix for https://github.com/modelcontextprotocol/inspector/issues/766
Trigger completions immediately for prompts rather than only on property updates so that you get the list of options without having to type the first character. See the issue.
https://github.com/modelcontextprotocol/inspector/issues/766
Compare this to the video in the issue: the drop down does not have the options populated before this fix.
https://github.com/user-attachments/assets/86abf014-3f0a-4830-b6ec-b1e9c8e0f45d
None.
N/A
> Fix issue 766 - Completions not populated until you start typing
