- bin/cli.js
- client/vite.config.ts
- package-lock.json
- package.json
This PR makes the client/server log to terminal which hopefully will make debugging easier when users have trouble. It also turns off minification which will give us some better stacks when users file issues
> Make debugging Inspector easier for users

- server/src/index.ts
Make sure we find the actual path to executables, which we don't get for free on Win32
> Enable using 'npx' as your command on Windows

- client/src/App.tsx
- Add failed requests to history with error messages for better debugging
- Persist selected tab in URL hash and restore on page load
- Fix formatting of timeout parameter parsing
> feat: improve request history and tab persistence

- client/src/components/Sidebar.tsx
Makes command, arguments, URL and environment variables easier to read and edit.
Monospace is easier to read for commands
Screenshot
None
> feat: use monospace font for all input fields in sidebar

- client/src/components/Sidebar.tsx
Adding a github link
Makes it easier for users to find the repo if they have bug reports or want to contribute.
See screenshot
None
> feat: add GitHub link to sidebar for bug reports and contributions

- client/src/components/DynamicJsonForm.tsx
- client/src/components/ToolsTab.tsx
Add Array Type Support for DynamicJsonForm
The existing DynamicJsonForm component only supported object-type parameters and lacked array type handling. This enhancement adds comprehensive support for array types, enabling the component to handle complex data structures that include arrays. This improvement allows the form to better accommodate various parameter configuration needs.
And improved the toolsbar.tsx file by refining the TypeScript type of the prop to JsonSchemaType.
The changes have been tested in the following scenarios:
- Creating and editing array-type parameters
- Adding and removing array items
- Handling nested array and object structures
- Testing array items with different data types (string, number, boolean)
No breaking changes. This is a feature enhancement that …
> Add an array input field to the ToolsTab using DynamicJsonForm.

- client/package.json
- package-lock.json
- server/package.json
> Bumped versions of sub packages

- client/src/lib/hooks/useConnection.ts
Brings back timeout feature from #108 and fixes #163
> Timeout search param

- client/src/lib/hooks/useConnection.ts
In useConnection.ts,
- import LoggingMessageNotificationSchema
- set onNotification as notification handler for LoggingMessageNotificationSchema
This fixes #184 
As #184 demonstrates, logging notifications from the server were not being displayed in the inspector.
I [added functionality](https://github.com/modelcontextprotocol/servers/pull/847) to the `modelcontextprotocol/servers` project, which sends randomly-leveled log messages every 15 seconds.
Nope.
> Add support for server logging messages

- client/package.json
- package-lock.json
- package.json
- server/package.json
> Bump version to 0.7.0

- README.md
I've noticed more discussions lately on remote development configurations so I think its worth calling this out in the docs for anyone who is thinking of deploying Inspector remotely, and who may be new to this.
N/A
No
> Add note on security considerations for proxy server

- client/src/components/DynamicJsonForm.tsx
- client/src/components/History.tsx
- client/src/components/JsonEditor.tsx
- client/src/components/JsonView.tsx
- client/src/components/PromptsTab.tsx
- client/src/components/ResourcesTab.tsx
- client/src/components/SamplingTab.tsx
- client/src/components/ToolsTab.tsx
Previously, JSON data was displayed as a plain string. This PR introduces a JSON View component with expand and collapse functionality to enhance readability and ease of data exploration.
The previous method of displaying JSON as plain text made it difficult to navigate and understand the data structure at a glance. Introducing a JSON View component significantly improves usability and debugging efficiency.
Tested thoroughly in a real application environment using various JSON datasets. Verified that the expand and collapse functionalities work correctly and JSON data is presented accurately.
None
- JSON View component has been implemented in a reusable manner.
- Maintained existing UI styling for the pre-tag to ensure visual consistency.
> feat: Add JSON View Component

- client/src/lib/useTheme.ts
perf: add `useMemo` to the return value of `useTheme`
Improve performance
It does not modify the functionality, I test locally with `npm run dev:windows` and toggle theme manually to make sure it works.
No
> perf: add `useMemo` to the return value of `useTheme`

- client/src/components/__tests__/ToolsTab.test.tsx
Adding ToolsTab test to repro the issue being resolved by https://github.com/modelcontextprotocol/inspector/pull/234
> Add failing test to repro issue 154

- client/package.json
- package-lock.json
- package.json
- server/package.json
Bumping npm version to trigger release approval process.
> Bump version to 0.8.0

- client/package.json
- package.json
- server/package.json
* In client/package.json
- version bumped to 0.8.1
- typescript SDK version 0.8.0 (latest)
* In server/package.json
- version bumped to 0.8.1
- typescript SDK version 0.8.0 (latest)
* In client/package.json
- version bumped to 0.8.1
- inspector-client bumped to 0.8.1
- inspector-server bumped to 0.8.1
Publish [fixes to some connection issues](https://github.com/modelcontextprotocol/inspector/pull/253) that showed up in 0.8.0
Part of my test with the `server-everything` server. 
Video: https://github.com/user-attachments/assets/1cb1698e-7427-433a-b4d2-d878a256a03d
NEEDS OAuth test.
> Bump version to 0.8.1

- package-lock.json
Include the new package-lock.json
Overlooked in previous PR
> Bump to version 0.8.1 - package-lock.json

- README.md
- client/package.json
- package-lock.json
- package.json
- server/package.json
Let's use the  1.9.0 Typescript SDK 
* In package.json
- Use inspector-[client|server] version 0.8.2
* In [client|server]/package.json
- New version to 0.8.2
- Use typescript SDK version 1.9.0
* In package-lock.json
- above changes
- sdk dependency's version increased: node_modules/@modelcontextprotocol/sdk/node_modules/pkce-challenge
* In README.md
- Point to inspector screenshot's rawcontent address so it doesn't appear as a broken image in the NPM package view.
The latest version of the SDK was released, so we want to build on it going forward.
Built locally, ran tests. Manually tested via Inspector, connecting to servers (with/without oauth), using tools, etc.
No.
> Use sdk 1.9.0

- client/src/components/DynamicJsonForm.tsx
- client/src/components/JsonView.tsx
- client/src/components/ToolsTab.tsx
- client/src/components/__tests__/DynamicJsonForm.test.tsx
- client/src/utils/__tests__/jsonUtils.test.ts
- client/src/utils/__tests__/schemaUtils.test.ts
- client/src/utils/jsonUtils.ts
- client/src/utils/schemaUtils.ts
refactor(json): Consolidate JSON utilities and type definitions
> refactor(json): Consolidate JSON utilities and type definitions

- client/src/components/ui/button.tsx
- client/src/components/ui/input.tsx
- client/src/components/ui/textarea.tsx
- client/src/hooks/use-toast.ts
- client/src/lib/hooks/useCompletionState.ts
- client/src/lib/useTheme.ts
This PR fixes the issue [#291](https://github.com/modelcontextprotocol/inspector/issues/291).
1. Removed unused error variable in catch block
- Reference: [Optional catch binding in Typescript](https://stackoverflow.com/questions/21624456/can-i-use-a-try-catch-in-javascript-without-specifying-the-catch-argument-identi)
2. Changed `actionTypes` type to enum
- Since actionTypes was declared and used only to infer its type
3. Removed unnecessary interface extensions
- Since there were no members declared in the interface, it is equivalent to its extended parent 
4. Removed unused export component
-  The `buttonVariants` component was exported but was not used elsewhere
5. Added the missing dependencies to useMemo
6. Fixed the inline function issue by changing it to useMemo
-  Used useMemo to …
> Fix - Lint warnings and errors in client

- client/src/components/PromptsTab.tsx
- client/src/components/ResourcesTab.tsx
- client/src/components/ToolsTab.tsx
- client/src/components/ui/tabs.tsx
There were inconsistencies between the margins of all tabs.
Dark mode colors where not consistent
Adding consistency in the UI
No
> fix dark mode color and padding for the tab item

- cli/package.json
- client/package.json
- package-lock.json
- package.json
- server/package.json
Bump version to 0.10.0 in
* cli/package.json
* client/package.json
* server/package.json
* package.json
- also bump npm dependencies for cli, client, and server to 0.10.0
* package-lock.json
* Bump typescript-sdk version to 1.10.0 throughout
Although we may not have streamable http in the inspector yet as we wait for the next SDK release, we do have major improvements in OAuth a new CLI.  
Build, test, lint, etc. But until published, it isn't really using the bumped dependency versions.
Nope.
> Bump to 0.10.0

- cli/package.json
- client/package.json
- package-lock.json
- package.json
- server/package.json
Bump inspector, cli, client, server to 0.10.1
The postmortem for 0.10.0 [is here](https://github.com/modelcontextprotocol/inspector/issues/326#issuecomment-2814035294).
tl;DR - looks like build wasn't done before the final publish step.
Verified all the proper changes were made in package.json for project, cli, client, and server, as well as the package.lock.json.
Nope.
> Bump inspector to 0.10.1

- package.json
* In package.json
- replaced `prepare` script, which will cause automatic build after npm install
Automatically run build after `npm install`. It was ommitted from the previous PR. Important because the counterbalancing explicit build was removed from the main.yml
Ran locally. Builds after install.
> Bump release to 0.11.0 - Amendment

- cli/package.json
- client/package.json
- package-lock.json
- package.json
- server/package.json
> 0.13.0 bump version

- client/src/components/Sidebar.tsx
- client/src/components/__tests__/Sidebar.test.tsx
The copying is meant to be generic, but mentioned Cursor explicitly in one spot.
Originally introduced here: https://github.com/modelcontextprotocol/inspector/pull/334
Text change only
no
> rework naming on config copy

- README.md
Clarifying what the different components of Inspector actually do.
N/A
No
> Add simple architecture overview with note on proxy role

- client/src/App.tsx
- client/src/components/__tests__/AuthDebugger.test.tsx
- client/src/components/__tests__/Sidebar.test.tsx
- client/src/lib/hooks/useConnection.ts
- package-lock.json
- server/src/index.ts
> Fixing linting issues from previous bug fix

- cli/package.json
- client/package.json
- package-lock.json
- package.json
- server/package.json
Bumped to 0.14.3 in all the places using the newly added `update-version.js` script.
Need to do a patch level release in order to test the ghcr docker container publishing feature added to main.yml in #257
> Bump version to 0.14.3

- package-lock.json
Wasn't fully updated with dependency versions in #532
> Update package-lock.json after SDK version bump

- cli/package.json
- client/package.json
- package-lock.json
- package.json
- server/package.json
Patch to include fixes to webclient startup in https://github.com/modelcontextprotocol/inspector/pull/604
Nope.
> Bump version to 0.16.1

- .github/workflows/claude.yml
We recently added Claude to the reference servers repo with these settings, so I think we can apply the same settings here to open up the action to more people for testing in this repo.
Same config has been added to the reference servers repo and its been useful there from testing it there so far.
No
If we do see people spamming this or any other concerns, lets raise them in the Discord maintainer channel.  I think we can also add some additional instructions here to help with creating a more consistent PR template in the near future, but for now lets merge as-is.
> Update CC GitHub Action to have same config as servers repo action
